import {CapabilityDefinition} from "../core/types.js";

export const ENGINEERING_CAPABILITIES:CapabilityDefinition[]=[
  {id:"ANALYSIS.SHAFT_TORQUE",domain:"analysis",purpose:"Calculate transmitted shaft torque",inputs:["powerKw","speedRpm"],outputs:["torqueNm"],risk:"LOW",providers:["numerical-analysis"],status:"VERIFIED"},
  {id:"ANALYSIS.SHAFT_SIZE",domain:"analysis",purpose:"Preliminarily size a solid shaft",inputs:["powerKw","speedRpm","bendingMomentNm","allowableShearStressMpa"],outputs:["minimumDiameterMm"],risk:"MEDIUM",providers:["numerical-analysis"],status:"PILOT"},
  {id:"UNITS.CONVERT",domain:"computation",purpose:"Convert an engineering quantity between compatible units",inputs:["value","fromUnit","toUnit"],outputs:["value","unit"],risk:"LOW",providers:["computation.pint-sympy-scipy"],status:"PILOT"},
  {id:"UNITS.CHECK_DIMENSIONS",domain:"computation",purpose:"Check dimensional compatibility of engineering quantities",inputs:["quantities"],outputs:["compatible","dimensions"],risk:"LOW",providers:["computation.pint-sympy-scipy"],status:"PILOT"},
  {id:"MATH.SYMBOLIC_SOLVE",domain:"computation",purpose:"Solve a bounded symbolic engineering equation",inputs:["equation","variables","knownValues"],outputs:["solutions"],risk:"MEDIUM",providers:["computation.sympy"],status:"EXPERIMENTAL"},
  {id:"MATH.NUMERICAL_SOLVE",domain:"computation",purpose:"Solve a bounded numerical engineering problem",inputs:["function","initialGuess","bounds"],outputs:["solution","residual"],risk:"MEDIUM",providers:["computation.scipy"],status:"EXPERIMENTAL"},
  {id:"MATH.OPTIMIZE",domain:"computation",purpose:"Optimize a bounded engineering objective under explicit constraints",inputs:["objective","variables","constraints","bounds"],outputs:["solution","objectiveValue"],risk:"MEDIUM",providers:["computation.scipy"],status:"EXPERIMENTAL"},
  {id:"MATH.CROSS_VALIDATE",domain:"computation",purpose:"Compare independently computed results and report agreement",inputs:["calculations"],outputs:["comparison","confidence"],risk:"LOW",providers:["computation.cross-check"],status:"EXPERIMENTAL"},
  {id:"ANALYSIS.STATIC_STRUCTURAL",domain:"simulation",purpose:"Run static structural FEA",inputs:["model","loads","constraints","mesh"],outputs:["stress","displacement","reaction_forces"],risk:"HIGH",providers:["ansys.pymechanical-worker","ansys.pymechanical"],status:"PILOT"},
  {id:"CAD.CREATE_PART",domain:"cad",purpose:"Create a parametric mechanical part",inputs:["parameters","geometry_program"],outputs:["cad_artifact"],risk:"MEDIUM",providers:["cad.build123d","cad.cadquery","cad.freecad","onshape.gpambrozio","onshape.casys"],status:"EXPERIMENTAL"},
  {id:"CAD.EXECUTE_GENERATED_SOURCE",domain:"cad",purpose:"Execute generated parametric CAD source in an isolated runtime",inputs:["source","backend"],outputs:["cad_artifact"],risk:"HIGH",providers:["cad.worker","cad.build123d","cad.cadquery"],status:"PILOT"},
  {id:"CAD.VALIDATE_GEOMETRY",domain:"cad",purpose:"Validate solid geometry and topology",inputs:["cad_artifact"],outputs:["geometry_validation"],risk:"MEDIUM",providers:["cad.occt","cad.freecad"],status:"EXPERIMENTAL"},
  {id:"CAD.EXPORT_STEP",domain:"cad",purpose:"Export a CAD artifact as STEP",inputs:["cad_artifact"],outputs:["step_artifact"],risk:"LOW",providers:["cad.occt","cad.build123d","cad.freecad","onshape.gpambrozio","onshape.casys"],status:"EXPERIMENTAL"},
  {id:"PLM.QUERY_ITEM",domain:"plm",purpose:"Query engineering item and lifecycle information",inputs:["itemId"],outputs:["plm_item"],risk:"LOW",providers:["plm.odooplm"],status:"EXPERIMENTAL"},
  {id:"PLM.CREATE_REVISION",domain:"plm",purpose:"Create or prepare an engineering revision",inputs:["itemId","changeDescription"],outputs:["revision"],risk:"HIGH",providers:["plm.odooplm"],status:"EXPERIMENTAL"}
];