create type public.engineering_project_status as enum ('ACTIVE','BLOCKED','COMPLETE');
create type public.engineering_project_role as enum ('ENGINEER','REVIEWER','ADMIN','AGENT');
create table public.engineering_projects (id uuid primary key default gen_random_uuid(),owner_id uuid not null references auth.users(id) on delete restrict,name text not null check (length(trim(name)) > 0),stage text not null default 'PROBLEM',status public.engineering_project_status not null default 'ACTIVE',revision bigint not null default 1 check (revision > 0),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.engineering_project_memberships (project_id uuid not null references public.engineering_projects(id) on delete cascade,user_id uuid not null references auth.users(id) on delete cascade,role public.engineering_project_role not null,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),primary key (project_id,user_id));
create table public.engineering_workspaces (project_id uuid primary key references public.engineering_projects(id) on delete cascade,revision bigint not null default 1 check (revision > 0),snapshot jsonb not null,saved_at timestamptz not null default now(),constraint engineering_workspaces_snapshot_object check (jsonb_typeof(snapshot) = 'object'));
create index engineering_project_memberships_user_project_idx on public.engineering_project_memberships(user_id,project_id);
create index engineering_projects_owner_idx on public.engineering_projects(owner_id);
create schema if not exists private;
create or replace function private.is_project_member(target_project_id uuid) returns boolean language sql stable security definer set search_path = '' as $$ select exists (select 1 from public.engineering_project_memberships m where m.project_id=target_project_id and m.user_id=(select auth.uid())); $$;
create or replace function private.has_project_role(target_project_id uuid,allowed_roles public.engineering_project_role[]) returns boolean language sql stable security definer set search_path = '' as $$ select exists (select 1 from public.engineering_project_memberships m where m.project_id=target_project_id and m.user_id=(select auth.uid()) and m.role=any(allowed_roles)); $$;
revoke execute on function private.is_project_member(uuid) from public,anon;
revoke execute on function private.has_project_role(uuid,public.engineering_project_role[]) from public,anon;
grant usage on schema private to authenticated;
grant execute on function private.is_project_member(uuid) to authenticated;
grant execute on function private.has_project_role(uuid,public.engineering_project_role[]) to authenticated;
create or replace function private.add_project_owner_membership() returns trigger language plpgsql security definer set search_path = '' as $$ begin insert into public.engineering_project_memberships(project_id,user_id,role) values (new.id,new.owner_id,'ADMIN'); return new; end; $$;
revoke execute on function private.add_project_owner_membership() from public,anon,authenticated;
drop trigger if exists engineering_projects_owner_membership on public.engineering_projects;
create trigger engineering_projects_owner_membership after insert on public.engineering_projects for each row execute function private.add_project_owner_membership();
alter table public.engineering_projects enable row level security;
alter table public.engineering_project_memberships enable row level security;
alter table public.engineering_workspaces enable row level security;
revoke all on table public.engineering_projects from anon,authenticated;
revoke all on table public.engineering_project_memberships from anon,authenticated;
revoke all on table public.engineering_workspaces from anon,authenticated;
grant select,insert,update on table public.engineering_projects to authenticated;
grant select,insert,update,delete on table public.engineering_project_memberships to authenticated;
grant select,insert,update on table public.engineering_workspaces to authenticated;
create policy engineering_projects_select_member on public.engineering_projects for select to authenticated using ((select private.is_project_member(id)));
create policy engineering_projects_insert_owner on public.engineering_projects for insert to authenticated with check ((select auth.uid())=owner_id);
create policy engineering_projects_update_manager on public.engineering_projects for update to authenticated using ((select private.has_project_role(id,array['ADMIN','ENGINEER']::public.engineering_project_role[]))) with check ((select private.has_project_role(id,array['ADMIN','ENGINEER']::public.engineering_project_role[])));
create policy project_memberships_select_member on public.engineering_project_memberships for select to authenticated using ((select private.is_project_member(project_id)));
create policy project_memberships_insert_manager on public.engineering_project_memberships for insert to authenticated with check ((select private.has_project_role(project_id,array['ADMIN']::public.engineering_project_role[])));
create policy project_memberships_update_manager on public.engineering_project_memberships for update to authenticated using ((select private.has_project_role(project_id,array['ADMIN']::public.engineering_project_role[]))) with check ((select private.has_project_role(project_id,array['ADMIN']::public.engineering_project_role[])));
create policy project_memberships_delete_manager on public.engineering_project_memberships for delete to authenticated using ((select private.has_project_role(project_id,array['ADMIN']::public.engineering_project_role[])));
create policy engineering_workspaces_select_member on public.engineering_workspaces for select to authenticated using ((select private.is_project_member(project_id)));
create policy engineering_workspaces_insert_manager on public.engineering_workspaces for insert to authenticated with check ((select private.has_project_role(project_id,array['ADMIN','ENGINEER']::public.engineering_project_role[])));
create policy engineering_workspaces_update_manager on public.engineering_workspaces for update to authenticated using ((select private.has_project_role(project_id,array['ADMIN','ENGINEER']::public.engineering_project_role[]))) with check ((select private.has_project_role(project_id,array['ADMIN','ENGINEER']::public.engineering_project_role[])));
